// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8o0ZWn7b5zxEU9qJaeDNLjL1ENXZtys',
    appId: '1:88536177205:web:cdd54a5e4d0afdf78cef7c',
    messagingSenderId: '88536177205',
    projectId: 'chatify-270ff',
    authDomain: 'chatify-270ff.firebaseapp.com',
    storageBucket: 'chatify-270ff.firebasestorage.app',
    measurementId: 'G-YD3G8JB4RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEyZDP-_Hn98nRTG6mWYe9rDfj-Bw1LY',
    appId: '1:88536177205:android:cc74246d6fb8d4198cef7c',
    messagingSenderId: '88536177205',
    projectId: 'chatify-270ff',
    storageBucket: 'chatify-270ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu41k8FA4gERkQZCEDJePfDqWxbgdHLxw',
    appId: '1:88536177205:ios:cf9d4ee1543b3c8c8cef7c',
    messagingSenderId: '88536177205',
    projectId: 'chatify-270ff',
    storageBucket: 'chatify-270ff.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu41k8FA4gERkQZCEDJePfDqWxbgdHLxw',
    appId: '1:88536177205:ios:cf9d4ee1543b3c8c8cef7c',
    messagingSenderId: '88536177205',
    projectId: 'chatify-270ff',
    storageBucket: 'chatify-270ff.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx8o0ZWn7b5zxEU9qJaeDNLjL1ENXZtys',
    appId: '1:88536177205:web:53953b463b61cd4d8cef7c',
    messagingSenderId: '88536177205',
    projectId: 'chatify-270ff',
    authDomain: 'chatify-270ff.firebaseapp.com',
    storageBucket: 'chatify-270ff.firebasestorage.app',
    measurementId: 'G-69HWZHTMJQ',
  );
}
